# Adapted from https://gist.github.com/jeffbr13/08751e42c9355cc44f5d
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all safe packages
  apt:
    upgrade: safe

- name: Install unattended upgrades (Debian/Ubuntu only)
  apt:
    pkg: unattended-upgrades
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# - name: 'Make sure unattended-upgrades only installs from $ubuntu_release-security'
#   lineinfile: 'dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent'
#   when: ansible_distribution == 'Ubuntu'

- name: ubuntu | ensuring Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  apt_repository:
    repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
    state: present

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=present
  with_items:
    - acl
    - apache2
    - apt-transport-https
    - apticron
    - aptitude
    - build-essential
    - debian-goodies
    - fail2ban
    - git
    - git-core
    - htop
    - iftop
    - iotop
    - libapache2-mod-wsgi
    - libffi-dev
    - libssl-dev
    - libpq5
    - libpq-dev
    - nginx
    - python-pip
    - python3-pip
    - python-psycopg2
    - python-pycurl
    - software-properties-common
    - python-dev
    - python-virtualenv
    - python-setuptools
    - postgresql
    - postgresql-contrib
    - solr-jetty
    - redis-server
    - screen
    - sudo
    - wget
    - openjdk-8-jdk

  when: ansible_pkg_mgr == 'apt'

- name: Enable passwordless sudo
  lineinfile: 'dest=/etc/sudoers regexp="sudo ALL=NOPASSWD: ALL" line="%sudo ALL=NOPASSWD: ALL" state=present'
