# Variables associated with current role

ckan_python_env_path: "/usr/lib/ckan/ckan-env"
ckan_pip_dependencies:
  - { name: 'setuptools', version: '36.1.0'}
  - { name: 'wheel', version: '0.31.1'}
  - { name: 'urllib3[secure]', version: '1.19.1' }

ckan_config_file: "/etc/ckan/default/development.ini"
ckan_domain: localhost
solr_domain: 127.0.0.1


postgresql_user: postgres
postgresql_group: postgres
ckan_db_name: ckan
db_user: ckan_user
db_password: ckan_pass

postgresql_version: "10"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_daemon: postgresql

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}

postgresql_locales:
  - 'en_US.UTF-8'

ckan_source_source: "{{ ckan_python_env_path }}/src/ckan/ckan/config/solr/schema.xml"
ckan_solr_conf_path: "/var/solr/data/ckan/conf"
#Datastore
datastore_db: ckan_datastore
datastore_user: ckan_ds
datastore_pass: ckan_ds_pass

#sysadmin
ckan_admin: admin
ckan_admin_email: info@civicdatalab.in
ckan_admin_username: admin
ckan_admin_password: Abcd1234